/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "Console/Console.h"



int main(void)
{
	MCU_Clock_Setup();
	Delay_Config();
	Console_Init(9600);



    /* Loop forever */
	for(;;)
	{
		printConsole("Hello \r\n");
		Delay_s(1);
	}
}
